#
# Contains the full stack of the RTB4FREe stack (not including elk))
# Does contain zookeeper and kafka, postgres and minio
#
version: "3"

services:
  zookeeper:
    image: "zookeeper"
    ports:
     - "2181:2181"

  kafka:
    image: "ches/kafka"
    environment:
      ZOOKEEPER_IP: "zookeeper"
    ports:
      - "9092:9092"
    restart: always
    depends_on:
      - zookeeper

  sqldb:
    image: "postgres"
    environment:
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"
    volumes:
      - /tmp/data:/var/lib/postgresql/data
      
  bidder:
    image: jacamars/newbidder
    environment:
      BROKERLIST: "kafka:9092"
      EXTERNAL: "http://localhost:8080"
      JDBC: "jdbc:postgresql://sqldb/postgres?user=postgres&password=postgres"
      S3BUCKET: ""
      S3REGION: "us-east-1"
      S3ENDPOINT: "http://minio:9000"
      AWSACCESSKEY: "${AWSACCESSKEY}"
      AWSSECRETKEY: "${AWSSECRETKEY}"
      GOOGLE_EKEY: ""
      GOOGLE_IKEY: ""
      OPENX_EKEY: ""
      OPENX_IKEY: ""
      ADX_EKEY:   ""
      ADX_IKEY:   ""
    #volumes:
    #  - /payday.json:./Campaigns/payday.json
    ports:
      - "8081:8080"
    #  - "8155:8155"
    #  - "5701:5701"
    #  - "7379:7379"
    command: bash -c "./wait-for-it.sh kafka:9092 -t 120 && ./wait-for-it.sh sqldb:5432 -t 120 && ./wait-for-it.sh minio:9000 -t 120 && ./rtb4free s3://config/payday.json"
    
  minio:
    image: minio/minio
    ports:
      - '9000:9000'
    environment:
      - MINIO_ACCESS_KEY=${AWSACCESSKEY}
      - MINIO_SECRET_KEY=${AWSSECRETKEY}
    volumes:
      - /tmp/s3:/data
    command: server /data
    
  doc:
    image: jacamars/rtbx-website
    ports:
      - "9090:80"
