#
# Contains the full stack of the RTB4FREe stack (not including crosstalk, elk, mysql or campaign manager)
# Does contain zookeeper and kafka.
#
version: "3"

services:
  zookeeper:
    image: "zookeeper"
    ports:
     - "2181:2181"

  kafka:
    image: "ches/kafka"
    environment:
      ZOOKEEPER_IP: "zookeeper"
    ports:
      - "9092:9092"
    restart: always
    depends_on:
      - zookeeper

  sqldb:
    image: "postgres"
    environment:
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"
    volumes:
      - /tmp/data:/var/lib/postgresql/data
      
  bidder:
    image: jacamars/newbidder
    environment:
      BROKERLIST: "kafka:9092"
      EXTERNAL: "http://localhost:8080"
      JDBC: "jdbc:postgresql://sqldb/postgres?user=postgres&password=postgres"
      S3BUCKET: ""
      S3REGION: ""
      S3SECRETKEY: ""
      S3ACCESSKEY: ""
      GOOGLE_EKEY: ""
      GOOGLE_IKEY: ""
      OPENX_EKEY: ""
      OPENX_IKEY: ""
      ADX_EKEY:   ""
      ADX_IKEY:   ""
    ports:
      - "8080:8080"
      - "8155:8155"
      - "5701:5701"
      - "7379:7379"
    depends_on:
      - kafka
    command: bash -c "./wait-for-it.sh kafka:9092 -t 120 && ./wait-for-it.sh sqldb:5432 && sleep 1; ./rtb4free Campaigns/payday.json"
