version: "3"

services:

  zookeeper:
    image: "zookeeper"
    #ports:
    # - "2181:2181"

  kafka:
    image: "ches/kafka"
    environment:
      ZOOKEEPER_IP: "zookeeper"
    #ports:
    #  - "9092:9092"
    restart: always
    depends_on:
      - zookeeper

  bidder:
    image: "jacamars/rtb4free:J11"
    environment:
      GDPR_MODE: "true"
      BROKERLIST: "kafka:9092"
      PUBSUB: "zerospike"
      EXTERNAL: "http://localhost"
      ADMINPORT: "8155"
      ACCOUNTING: "NONE"
      FREQGOV: "false"
      INDEXPAGE: "/index.html"
      BIDSWITCH_ID: "5678"
    ports:
      - "8080:8080"
      - "8155:8155"
      - "5701:5701"
    #  - "7379:7379"
    #  - "7000:7000"
    restart: always
    #volumes:
    #  - "./database.json:/database.json"
    #  - "./payday.json:/Campaigns/payday.json"
    depends_on:
      - kafka
      - zerospike
    command: bash -c "sleep 5 && ./wait-for-it.sh kafka:9092 -t 120 && sleep 1; ./rtb4free"
    #command:  bash -c "sleep 5 && ./wait-for-it.sh kafka:9092 -t 120 && sleep 1; ./rtb4free-jmx"

  simulator:
    image: "jacamars/rtb4free:v1"
    environment:
      BIDDER: "bidder:8080"
      WIN:    "10"
      PIXEL:  "95"
      CLICK:  "2"
      SLEEP:  "100"
    command: bash -c "./wait-for-it.sh bidder:8080 -t 120 && sleep 60;  ./load-elastic -host $$BIDDER -win $$WIN -pixel $$PIXEL -click $$CLICK -file data/requests -sleep $$SLEEP"
  
