#
# Contains a stub postgres
#
version: "3"

services:
 
  sqldb:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"
    volumes:
      - /tmp/data:/var/lib/postgresql/data

