version: "3"

services:
  zookeeper:
    image: "zookeeper"
    ports:
      - "2181:2181"

  kafka:
    image: "ches/kafka"
    environment:
      ZOOKEEPER_IP: "zookeeper"
    ports:
      - "9092:9092"
        
  postgres:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"
    volumes:
      - /tmp/data:/var/lib/postgresql/data
