version: "3"

services:
  zookeeper:
    image: "zookeeper"
    ports:
      - "2181:2181"

  kafka:
    image: "ches/kafka"
    environment:
      ZOOKEEPER_IP: "zookeeper"
    ports:
      - "9092:9092"
        
  dbpg:
#    user: "1000:1000"
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  web:
#    user: "1000:1000"
    image: ploh/rtbadmin_open_pg
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
#    command: sleep infinity
    ports:
      - "3000:3000"
    environment:
      - CUSTOMER_NAME=RTB4FREE
      - RTB4FREE_DATABASE_HOST=dbpg
      - RTB4FREE_DATABASE_PORT=5432
      - RTB4FREE_DATABASE_USERNAME=postgres
      - RTB4FREE_DATABASE_PASSWORD=postgres
      - RTB_CROSSTALK_REGION_HOSTS={"US" => "outside"}
      - RTB4FREE_DATABASE_NAME=rtb4free
      - ELASTICSEARCH_ENABLE=false
      - ELASTICSEARCH_HOST=
      - ELASTICSEARCH_KIBANA_URL=
#    volumes:
#      - .:/rtb4free_admin
    depends_on:
      - dbpg
    extra_hosts:
      - "outside:10.0.0.10"

