---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pgdata"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels: 
    app: rtb-postgres
spec:
  volumes:
  - name: postgresql
    persistentVolumeClaim:
      claimName: postgres-pv-claim
  containers:
  - image: postgres:12
    name: db
    env:
    - name: POSTGRES_PASSWORD
      value: "postgres"
    - name: POSTGRES_USER
      value: postgres
#    - name: POSTGRES_DB
#      value: xxx
    ports:
    - containerPort: 5432
      name: postgresql5432
    volumeMounts:
    - name: postgresql
      mountPath: /var/lib/postgresql/data
    livenessProbe:
      exec:
        command:
        - pg_isready
        - -h
        - localhost
        - -U
        - postgres
      initialDelaySeconds: 30
      timeoutSeconds: 10
    readinessProbe:
      exec:
        command:
        - pg_isready
        - -h
        - localhost
        - -U
        - postgres
      initialDelaySeconds: 30
      timeoutSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: rtb-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
