insert into users (customer_id, 
	sub_id,
	username, 
	password,
	company,
	email,
	telephone,
	firstname,
	lastname,
	address,
	citystate,
	country,
	postalcode,
	about,
	picture,
	description,
	title
	) values(
	'rtb4free',
	'superuser',
	'ben.faul@rtb4free.com',
	'zulu',
	'Jacamars, Inc',
	'ben.faul@rtb4free.com',
	'310-467-0646',
	'Ben',
	'Faul',
	'3820 Del Amo Blvd #226',
	'Torrance, CA.',
	'USA',
	'90503',
	'Chief cook and dish-washer.',
	'https://i.kym-cdn.com/entries/icons/original/000/004/006/YUNO.jpg',
	'Will sthis stuff ever get done???',
	'Head Peon'
);

insert into users (customer_id, 
	sub_id,
	username, 
	password,
	company,
	email,
	telephone,
	firstname,
	lastname,
	address,
	citystate,
	country,
	postalcode,
	about,
	picture,
	description,
	title
	) values(
	'test',
	'superuser',
	'test.test@test.com',
	'test',
	'Jacamars, Inc',
	'test.test@test.com',
	'666-666-6666',
	'Test',
	'Test',
	'3820 Del Amo Blvd #226',
	'Torrance, CA.',
	'USA',
	'90503',
	'Test',
	'https://i.kym-cdn.com/entries/icons/original/000/004/006/YUNO.jpg',
	'Is this stuff tested???',
	'Head Tester'
);

