#!/bin/sh
#
# This loads the Database cache
#
java -Dlog4j.configuration="file:log4j-nolog.properties" \
	 -Xmx4096m \
	 --add-modules java.se \
	 --add-exports java.base/jdk.internal.ref=ALL-UNNAMED \
	 --add-opens java.base/java.lang=ALL-UNNAMED \
	 --add-opens java.base/java.nio=ALL-UNNAMED \
	 --add-opens java.base/sun.nio.ch=ALL-UNNAMED \
	 --add-opens java.management/sun.management=ALL-UNNAMED \
	 --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED \
	  -cp target/RTB5-0.0.1-SNAPSHOT.jarcom.jacamars.dsp.rtb.tools.Commands -command list-bidders 
	 
