#!/bin/sh
#
# This runs the RTB4FREE server
#
java -Dlog4j2.configurationFile="file:log4j2.properties"  \
	 -Xmx8g \
	 --add-modules java.se \
	 --add-exports java.base/jdk.internal.ref=ALL-UNNAMED \
	 --add-opens java.base/java.lang=ALL-UNNAMED \
	 --add-opens java.base/java.nio=ALL-UNNAMED \
	 --add-opens java.base/sun.nio.ch=ALL-UNNAMED \
	 --add-opens java.management/sun.management=ALL-UNNAMED \
	 --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED \
	 -cp target/RTB5-0.0.1-SNAPSHOT-jar-with-dependencies.jar com.jacamars.dsp.rtb.bidder.RTBServer $1 $2 $3 $4
