#!/bin/sh
#
# This runs the RTB4FREE server
#
java -Xmx4g \
-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=7000 \
-Dlog4j.configuration="file:log4j.properties" \
-cp target/RTB5-0.0.1-SNAPSHOT.jar com.jacamars.dsp.rtb.bidder.RTBServer -s xrtb $1 $2 $3